import type { Metadata } from "next";
import { Noto_Sans_Thai } from "next/font/google";
import "./globals.css";
import QueryProvider from "./providers/QueryProvider";

const localfonts = Noto_Sans_Thai({
  subsets: ["latin"],
  weight: ["400","500","600","700","800"]
});

export const metadata: Metadata = {
  title: "FOLIO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${localfonts.className} antialiased`}>
        <QueryProvider>
          {children}
        </QueryProvider>
      </body>
    </html>
  );
}
