/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/canon-at-1-retro-camera-9de66868d0f240e985da00c9480bfc82
Title: Canon AT-1 Retro Camera
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        ['#CAM0001_Body_#CAM0001_Textures_0']: THREE.Mesh
        ['#CAM0001_Battery_Check_#CAM0001_Textures_0']: THREE.Mesh
        ['#CAM0001_Spool_#CAM0001_Textures_0']: THREE.Mesh
        ['#CAM0001_Film_Advance_#CAM0001_Textures_0']: THREE.Mesh
        ['#CAM0001_Shutter_#CAM0001_Textures_0']: THREE.Mesh
        ['#CAM0001_Shutter_Speed_#CAM0001_Textures_0']: THREE.Mesh
    }
    materials: {
        CAM0001_Textures: THREE.MeshStandardMaterial
    }
}

export function Camera(props: React.JSX.IntrinsicElements['group']) {
    const { nodes, materials } = useGLTF('/model/canon_at-1_retro_camera.glb') as unknown as GLTFResult
    return (
        <group {...props} dispose={null}>

            <group rotation={[-Math.PI / 2, 0, 0]}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Body_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Battery_Check_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                    position={[0.0502525, 0.00094434, 0.07174423]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Spool_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                    position={[0.0502525, 0.00094434, 0.07519341]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Film_Advance_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                    position={[-0.05689258, 0.00094435, 0.07663463]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Shutter_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                    position={[-0.03496766, -0.00649043, 0.07595]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes['#CAM0001_Shutter_Speed_#CAM0001_Textures_0'].geometry}
                    material={materials.CAM0001_Textures}
                    position={[-0.05689258, 0.00094433, 0.07301308]}
                />
            </group>
        </group>
    )
}

useGLTF.preload('/model/canon_at-1_retro_camera.glb')
